input {
  kafka {
    bootstrap_servers => "kafka1:19092"
    topics => ["customer-events-raw"]
    group_id => "logstash-es-sink-group"
    codec => "json"
    auto_offset_reset => "earliest"
    decorate_events => "basic"
  }
}

filter {
  # Map mốc thời gian sự kiện vào trường @timestamp chuẩn của Elastic
  date {
    match => [ "event_time", "ISO8601" ]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["http://ecomflow-elasticsearch:9200"]
    index => "customer-events-raw-%{+YYYY.MM.dd}"
    # Cơ chế Idempotent: ghi đè nếu trùng event, chống duplicate
    document_id => "%{acc_id}_%{session_id}_%{event_time}"
  }

  stdout {
    codec => dots
  }
}
